In [1]:
import numpy as np 

## Broadcasting 

In [2]:
A = [1,2,3,4,5]
Output = [10,20,30,40,50]

In [4]:
res = [x*10 for x in A]
res

[10, 20, 30, 40, 50]

In [6]:
array = np.array(A)

In [8]:
array*10

array([10, 20, 30, 40, 50])

## Create and Array

In [13]:
array = np.array((1,2,3,4,5,6,7,8))
array

array([1, 2, 3, 4, 5, 6, 7, 8])

## Numpy Range function 

In [23]:
A = np.arange(20)
print(A.shape)
A = A.reshape(5,4)
print(A.shape)
print(A)

(20,)
(5, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [33]:
A = np.arange(10,20,2)
print(A)

[10 12 14 16 18]


##  Zero and Ones Array

In [27]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Linespace

In [37]:
np.linspace(10,21,10)

array([10.        , 11.22222222, 12.44444444, 13.66666667, 14.88888889,
       16.11111111, 17.33333333, 18.55555556, 19.77777778, 21.        ])

## Mathematical operation

In [39]:
A = np.array([1,2,3,4,5])
B = np.arange(10,15)
print(A,B)

[1 2 3 4 5] [10 11 12 13 14]


In [53]:
## ADD
print(A+B)
## Sub
print(A-B)
## Multiply
print(A*B)

## Power of number : 

print(A**2)
print(B**2)

[11 13 15 17 19]
[-9 -9 -9 -9 -9]
[10 22 36 52 70]
[ 1  4  9 16 25]
[100 121 144 169 196]


### Functional conditions

In [55]:
A >= 2

array([False,  True,  True,  True,  True])

## Metrics opeartions

In [60]:
A = np.array([1,2,3,4])
B = np.arange(10,14)
C = A.reshape((2,2))
D = B.reshape((2,2))
print(C)
print(D)

[[1 2]
 [3 4]]
[[10 11]
 [12 13]]


In [61]:
## Multiply two metrics: 
C*D

array([[10, 22],
       [36, 52]])

In [62]:
## Metrics Multiplication 
C@D


array([[34, 37],
       [78, 85]])

In [63]:
## Dot product
C.dot(D)

array([[34, 37],
       [78, 85]])

## Slicing of 2D the metrics

In [65]:
print(C)

[[1 2]
 [3 4]]


In [66]:
C[0][0]

1

In [77]:
C[0][0] , C[1][0]

(1, 3)

In [80]:
C[1,1]

4